TARGETS = ctrl path reglist tag packed
EXTRA_OBJS = gifprobe.o ../gs/emit_giftag.o ../gs/gsregs.o ../dma/dmatags.o ../dma/dmasend.o ../dma/vif/emit_vifcode.o

COMMON_DIR=../../common
include $(COMMON_DIR)/common-ee.mk
