TARGETS = basic intstall mpg mskpath3 stcycl stmod unpack unpackall vifcode control direct fifo mscal
EXTRA_OBJS = emit_vifcode.o ../../gs/emit_giftag.o ../../gs/gsregs.o ../dmatags.o ../dmasend.o ../../vu/assemble/block.o ../../vu/assemble/ops.o
EE_LIBS = -lg -ldma

COMMON_DIR=../../../common
include $(COMMON_DIR)/common-ee.mk
