TARGETS = doublebuffer ebit xgkick interrupt efu0
EXTRA_OBJS = ../assemble/block.o ../assemble/ops.o ../test_runner.o ../values.o \
	../../gs/emit_giftag.o ../../gs/gsregs.o \
	../../dma/dmasend.o ../../dma/dmatags.o ../../dma/vif/emit_vifcode.o
EE_LIBS = -lg

COMMON_DIR=../../../common
include $(COMMON_DIR)/common-ee.mk
