TARGETS = branch branchall divsqrt efu fdivdelay flags integer intloadstore loadstore move qdelay random randomstate
EXTRA_OBJS = ../assemble/block.o ../assemble/ops.o ../test_runner.o ../values.o
EE_LIBS = -lg

COMMON_DIR=../../../common
include $(COMMON_DIR)/common-ee.mk
