TARGETS = add clip float fmac macflags madd minmax mul opmul sub unary
EXTRA_OBJS = ../assemble/block.o ../assemble/ops.o ../test_runner.o ../values.o fmac_runner.o
EE_LIBS = -lg

COMMON_DIR=../../../common
include $(COMMON_DIR)/common-ee.mk
