TARGETS = label signal transfer crt csr readback prim scissor context blend ztest atest fog dither format texture
EXTRA_OBJS = emit_giftag.o gsregs.o ../dma/dmatags.o ../dma/dmasend.o drawprobe.o

COMMON_DIR=../../common
include $(COMMON_DIR)/common-ee.mk
