TARGETS = accumulate arithmetic callms convert divsqrt flags interlock transfer integer
EXTRA_OBJS = shared.o ../../vu/assemble/block.o ../../vu/assemble/ops.o
EE_LIBS =

COMMON_DIR=../../../common
include $(COMMON_DIR)/common-ee.mk
